<!DOCTYPE html><html lang="en" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>Draw Civil Work Drawing Via API &amp; C# | RainbowRunner</title><meta name="author" content="Rainbow Runner"><meta name="copyright" content="Rainbow Runner"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="AutoCAD 2019 Developer and ObjectARX 帮助 | Object Model (ActiveX) | Autodesk  IntruductionNow we draw the civil work drawing manually after calculating the load of the anchor bolt on the skid baseplat">
<meta property="og:type" content="article">
<meta property="og:title" content="Draw Civil Work Drawing Via API &amp; C#">
<meta property="og:url" content="https://rainbow-runner.github.io/2023/08/08/DrawCivilWorkDrawingViaAPI/index.html">
<meta property="og:site_name" content="RainbowRunner">
<meta property="og:description" content="AutoCAD 2019 Developer and ObjectARX 帮助 | Object Model (ActiveX) | Autodesk  IntruductionNow we draw the civil work drawing manually after calculating the load of the anchor bolt on the skid baseplat">
<meta property="og:locale" content="en_US">
<meta property="og:image" content="https://s3.bmp.ovh/imgs/2023/01/21/b9b5ab8e8b18eac5.jpg">
<meta property="article:published_time" content="2023-08-08T12:41:15.000Z">
<meta property="article:modified_time" content="2023-08-15T13:07:25.193Z">
<meta property="article:author" content="Rainbow Runner">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://s3.bmp.ovh/imgs/2023/01/21/b9b5ab8e8b18eac5.jpg"><link rel="shortcut icon" href="/img/favicon.png"><link rel="canonical" href="https://rainbow-runner.github.io/2023/08/08/DrawCivilWorkDrawingViaAPI/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="preconnect" href="//busuanzi.ibruce.info"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css" media="print" onload="this.media='all'"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.min.css" media="print" onload="this.media='all'"><script>const GLOBAL_CONFIG = { 
  root: '/',
  algolia: undefined,
  localSearch: undefined,
  translate: undefined,
  noticeOutdate: undefined,
  highlight: {"plugin":"highlighjs","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false},
  copy: {
    success: 'Copy successfully',
    error: 'Copy error',
    noSupport: 'The browser does not support'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  date_suffix: {
    just: 'Just',
    min: 'minutes ago',
    hour: 'hours ago',
    day: 'days ago',
    month: 'months ago'
  },
  copyright: undefined,
  lightbox: 'fancybox',
  Snackbar: undefined,
  source: {
    justifiedGallery: {
      js: 'https://cdn.jsdelivr.net/npm/flickr-justified-gallery/dist/fjGallery.min.js',
      css: 'https://cdn.jsdelivr.net/npm/flickr-justified-gallery/dist/fjGallery.min.css'
    }
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: 'Draw Civil Work Drawing Via API & C#',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  postUpdate: '2023-08-15 21:07:25'
}</script><noscript><style type="text/css">
  #nav {
    opacity: 1
  }
  .justified-gallery img {
    opacity: 1
  }

  #recent-posts time,
  #post-meta time {
    display: inline !important
  }
</style></noscript><script>(win=>{
    win.saveToLocal = {
      set: function setWithExpiry(key, value, ttl) {
        if (ttl === 0) return
        const now = new Date()
        const expiryDay = ttl * 86400000
        const item = {
          value: value,
          expiry: now.getTime() + expiryDay,
        }
        localStorage.setItem(key, JSON.stringify(item))
      },

      get: function getWithExpiry(key) {
        const itemStr = localStorage.getItem(key)

        if (!itemStr) {
          return undefined
        }
        const item = JSON.parse(itemStr)
        const now = new Date()

        if (now.getTime() > item.expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return item.value
      }
    }
  
    win.getScript = url => new Promise((resolve, reject) => {
      const script = document.createElement('script')
      script.src = url
      script.async = true
      script.onerror = reject
      script.onload = script.onreadystatechange = function() {
        const loadState = this.readyState
        if (loadState && loadState !== 'loaded' && loadState !== 'complete') return
        script.onload = script.onreadystatechange = null
        resolve()
      }
      document.head.appendChild(script)
    })
  
      win.activateDarkMode = function () {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      win.activateLightMode = function () {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }
      const t = saveToLocal.get('theme')
    
          if (t === 'dark') activateDarkMode()
          else if (t === 'light') activateLightMode()
        
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        if (asideStatus === 'hide') {
          document.documentElement.classList.add('hide-aside')
        } else {
          document.documentElement.classList.remove('hide-aside')
        }
      }
    
    const detectApple = () => {
      if(/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)){
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
    })(window)</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css"> <script src="/live2d-widget/autoload.js"></script><meta name="generator" content="Hexo 6.2.0"></head><body><div id="web_bg"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img is-center"><img src="https://i.loli.net/2021/02/24/5O1day2nriDzjSu.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="sidebar-site-data site-data is-center"><a href="/archives/"><div class="headline">Articles</div><div class="length-num">17</div></a><a href="/tags/"><div class="headline">Tags</div><div class="length-num">2</div></a><a href="/categories/"><div class="headline">Categories</div><div class="length-num">0</div></a></div><hr/><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Archives</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-list"></i><span> List</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" href="/music/"><i class="fa-fw fas fa-music"></i><span> Music</span></a></li><li><a class="site-page child" href="/movies/"><i class="fa-fw fas fa-video"></i><span> Movie</span></a></li></ul></div><div class="menus_item"><a class="site-page" href="/link/"><i class="fa-fw fas fa-link"></i><span> Link</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg" id="page-header" style="background-image: url('https://s3.bmp.ovh/imgs/2023/01/21/b9b5ab8e8b18eac5.jpg')"><nav id="nav"><span id="blog_name"><a id="site-name" href="/">RainbowRunner</a></span><div id="menus"><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Archives</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-list"></i><span> List</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" href="/music/"><i class="fa-fw fas fa-music"></i><span> Music</span></a></li><li><a class="site-page child" href="/movies/"><i class="fa-fw fas fa-video"></i><span> Movie</span></a></li></ul></div><div class="menus_item"><a class="site-page" href="/link/"><i class="fa-fw fas fa-link"></i><span> Link</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><a class="site-page"><i class="fas fa-bars fa-fw"></i></a></div></div></nav><div id="post-info"><h1 class="post-title">Draw Civil Work Drawing Via API &amp; C#</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">Created</span><time class="post-meta-date-created" datetime="2023-08-08T12:41:15.000Z" title="Created 2023-08-08 20:41:15">2023-08-08</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">Updated</span><time class="post-meta-date-updated" datetime="2023-08-15T13:07:25.193Z" title="Updated 2023-08-15 21:07:25">2023-08-15</time></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title="Draw Civil Work Drawing Via API &amp; C#"><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">Post View:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="post-content" id="article-container"><blockquote>
<p><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/OARX/2019/CHS/?guid=GUID-A809CD71-4655-44E2-B674-1FE200B9FE30">AutoCAD 2019 Developer and ObjectARX 帮助 | Object Model (ActiveX) | Autodesk</a></p>
</blockquote>
<h2 id="Intruduction"><a href="#Intruduction" class="headerlink" title="Intruduction"></a>Intruduction</h2><p>Now we draw the civil work drawing manually after calculating the load of the anchor bolt on the skid baseplate, which is inefficiency. In the excel form calculating the load, the dimension of the baseplate and the position of the anchor bolt have been definited, so we can drawing the civil work drawing via API automatically.</p>
<p>This blog will show the operation of the creating and editing the block through blocktable via AutoCAD’s API and how to edit the entity by using the handle of the object in CAD.</p>
<h2 id="How-to-create-and-add-the-entity-to-the-block"><a href="#How-to-create-and-add-the-entity-to-the-block" class="headerlink" title="How to create and add the entity to the block"></a>How to create and add the entity to the block</h2><figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">using</span> System;</span><br><span class="line"><span class="keyword">using</span> System.Collections.Generic;</span><br><span class="line"><span class="keyword">using</span> System.Linq;</span><br><span class="line"><span class="keyword">using</span> System.Text;</span><br><span class="line"><span class="keyword">using</span> System.Threading.Tasks;</span><br><span class="line"></span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.ApplicationServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.DatabaseServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.EditorInput;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Geometry;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Runtime;</span><br><span class="line"></span><br><span class="line"><span class="keyword">namespace</span> <span class="title">CivilWorkDrawing</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">public</span> <span class="keyword">class</span> <span class="title">Commands</span></span><br><span class="line">    &#123;</span><br><span class="line"></span><br><span class="line">        <span class="comment">//创建图形</span></span><br><span class="line">        <span class="comment">//转化为块参照</span></span><br><span class="line">        <span class="comment">//获取实体对象句柄</span></span><br><span class="line">        [<span class="meta">CommandMethod(<span class="string">&quot;CreateAndConvertToBlock&quot;</span>)</span>]</span><br><span class="line">        <span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">CreateAndConvertToBlock</span>()</span></span><br><span class="line">        &#123;</span><br><span class="line">            Document doc = Application.DocumentManager.MdiActiveDocument;</span><br><span class="line">            Database db = doc.Database;</span><br><span class="line">            Editor ed = doc.Editor;</span><br><span class="line"></span><br><span class="line">            Transaction tr = db.TransactionManager.StartTransaction();</span><br><span class="line">            </span><br><span class="line">            <span class="keyword">try</span></span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">using</span> (tr)</span><br><span class="line">                &#123;</span><br><span class="line">                    BlockTable bt = tr.GetObject(db.BlockTableId, OpenMode.ForWrite) <span class="keyword">as</span> BlockTable;</span><br><span class="line"></span><br><span class="line">                    <span class="comment">//创建图形</span></span><br><span class="line">                    Polyline polyline = <span class="keyword">new</span> Polyline();</span><br><span class="line">                    polyline.AddVertexAt(<span class="number">0</span>, <span class="keyword">new</span> Point2d(<span class="number">0</span>, <span class="number">0</span>), <span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">                    polyline.AddVertexAt(<span class="number">1</span>, <span class="keyword">new</span> Point2d(<span class="number">0</span>, <span class="number">10</span>), <span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">                    polyline.AddVertexAt(<span class="number">2</span>, <span class="keyword">new</span> Point2d(<span class="number">10</span>, <span class="number">10</span>), <span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">                    polyline.AddVertexAt(<span class="number">3</span>, <span class="keyword">new</span> Point2d(<span class="number">10</span>, <span class="number">0</span>), <span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">                    polyline.Closed = <span class="literal">true</span>;</span><br><span class="line"></span><br><span class="line">                    <span class="comment">//创建块参照</span></span><br><span class="line">                    BlockTableRecord btr = <span class="keyword">new</span> BlockTableRecord();</span><br><span class="line">                    btr.Name = <span class="string">&quot;CivilWorkDrawing&quot;</span>;</span><br><span class="line">                    btr.AppendEntity(polyline);</span><br><span class="line"></span><br><span class="line">                    bt.Add(btr);</span><br><span class="line">                    tr.AddNewlyCreatedDBObject(btr, <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">					<span class="comment">//模型空间中添加块参照</span></span><br><span class="line">                    BlockTableRecord currentSpace = tr.GetObject(db.CurrentSpaceId, OpenMode.ForWrite) <span class="keyword">as</span> BlockTableRecord;</span><br><span class="line"></span><br><span class="line">                    BlockReference blockRef = <span class="keyword">new</span> BlockReference(Point3d.Origin, btr.ObjectId);</span><br><span class="line">                    currentSpace.AppendEntity(blockRef);</span><br><span class="line">                    tr.AddNewlyCreatedDBObject(blockRef, <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">                    <span class="comment">//存储多段线句柄</span></span><br><span class="line">                    Handle polylineHandle = polyline.Handle;</span><br><span class="line">                    <span class="built_in">string</span> polylineHandleString = polylineHandle.Value.ToString();</span><br><span class="line">                    <span class="keyword">using</span> (System.IO.StreamWriter sw = System.IO.File.AppendText(<span class="string">&quot;C:/Users/RainbowRunner/Desktop/Handle.txt&quot;</span>))</span><br><span class="line">                    &#123;</span><br><span class="line">                        sw.WriteLine(polylineHandleString);</span><br><span class="line">                    &#125;</span><br><span class="line"></span><br><span class="line">                    tr.Commit();</span><br><span class="line"></span><br><span class="line">                &#125;</span><br><span class="line">                </span><br><span class="line">            &#125;</span><br><span class="line">            <span class="keyword">catch</span> (System.Exception ex)</span><br><span class="line">            &#123;</span><br><span class="line">                ed.WriteMessage(ex.ToString());</span><br><span class="line">            &#125;</span><br><span class="line">       </span><br><span class="line">        &#125;</span><br></pre></td></tr></table></figure>

<h2 id="How-to-create-new-layer-and-set-the-line-type-and-the-line-color"><a href="#How-to-create-new-layer-and-set-the-line-type-and-the-line-color" class="headerlink" title="How to create new layer and set the line type and  the line color"></a>How to create new layer and set the line type and  the line color</h2><figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">using</span> System;</span><br><span class="line"><span class="keyword">using</span> System.Collections.Generic;</span><br><span class="line"><span class="keyword">using</span> System.Linq;</span><br><span class="line"><span class="keyword">using</span> System.Text;</span><br><span class="line"><span class="keyword">using</span> System.Threading.Tasks;</span><br><span class="line"></span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.ApplicationServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.DatabaseServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.EditorInput;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Geometry;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Runtime;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Colors;</span><br><span class="line"></span><br><span class="line"><span class="keyword">namespace</span> <span class="title">CivilWorkDrawing</span></span><br><span class="line">&#123;</span><br><span class="line">    [<span class="meta">CommandMethod(<span class="string">&quot;LayerCreation&quot;</span>)</span>]</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">CreateLayerWithProperties</span>()</span></span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">//定义图层</span></span><br><span class="line">        <span class="built_in">string</span> CONTINUOUS_layer = <span class="string">&quot;粗实线&quot;</span>;</span><br><span class="line">        <span class="built_in">string</span> divide_layer = <span class="string">&quot;双点划线&quot;</span>;</span><br><span class="line">        <span class="built_in">string</span> centerLine_layer = <span class="string">&quot;中心线&quot;</span>;</span><br><span class="line"></span><br><span class="line">        <span class="comment">//获取当前文档和数据库</span></span><br><span class="line">        Document doc = Application.DocumentManager.MdiActiveDocument;</span><br><span class="line">        Database db = doc.Database;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">try</span></span><br><span class="line">        &#123;</span><br><span class="line">            <span class="comment">//开始事务</span></span><br><span class="line">            <span class="keyword">using</span> (Transaction tr = db.TransactionManager.StartTransaction())</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="comment">//获取图层表</span></span><br><span class="line">                LayerTable lt = tr.GetObject(db.LayerTableId, OpenMode.ForWrite) <span class="keyword">as</span> LayerTable;</span><br><span class="line"></span><br><span class="line">                <span class="comment">//粗实线</span></span><br><span class="line">                <span class="keyword">if</span> (!lt.Has(CONTINUOUS_layer))</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="comment">//创建新图层表记录</span></span><br><span class="line">                    LayerTableRecord ltr = <span class="keyword">new</span> LayerTableRecord();</span><br><span class="line">                    ltr.Name = CONTINUOUS_layer;</span><br><span class="line"></span><br><span class="line">                    <span class="comment">//设置线形</span></span><br><span class="line">                    ltr.LinetypeObjectId = SetLineType(<span class="string">&quot;粗实线&quot;</span>);</span><br><span class="line"></span><br><span class="line">                    <span class="comment">//设置颜色</span></span><br><span class="line">                    ltr.Color = Color.FromColorIndex(ColorMethod.ByAci, <span class="number">7</span>); <span class="comment">//7 - 白色</span></span><br><span class="line"></span><br><span class="line">                    ltr.LineWeight = LineWeight.LineWeight035;</span><br><span class="line"></span><br><span class="line">                    <span class="comment">//添加新图层记录表到图层表</span></span><br><span class="line">                    ObjectId ltId = lt.Add(ltr);</span><br><span class="line">                    tr.AddNewlyCreatedDBObject(ltr, <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">                    <span class="comment">//设置新图层为当前图层</span></span><br><span class="line">                    db.Clayer = ltId;</span><br><span class="line"></span><br><span class="line">                    <span class="comment">//提交事务</span></span><br><span class="line">                    tr.Commit();</span><br><span class="line"></span><br><span class="line">                    doc.Editor.WriteMessage(<span class="string">$&quot;已创建新图层：<span class="subst">&#123;CONTINUOUS_layer&#125;</span>&quot;</span>);</span><br><span class="line">                &#125;</span><br><span class="line">                <span class="keyword">else</span></span><br><span class="line">                &#123;</span><br><span class="line">                    doc.Editor.WriteMessage(<span class="string">$&quot;图层：“<span class="subst">&#123;CONTINUOUS_layer&#125;</span>”已存在&quot;</span>);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">catch</span> (System.Exception ex)</span><br><span class="line">        &#123;</span><br><span class="line">            doc.Editor.WriteMessage(ex.ToString());</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">private</span> <span class="keyword">static</span> ObjectId <span class="title">SetLineType</span>(<span class="params"><span class="built_in">string</span> linetypeName</span>)</span></span><br><span class="line">    &#123;</span><br><span class="line">        Document doc = Application.DocumentManager.MdiActiveDocument;</span><br><span class="line">        Database db = doc.Database;</span><br><span class="line"></span><br><span class="line">        <span class="comment">//获取线型表</span></span><br><span class="line">        LinetypeTable lt = doc.Database.LinetypeTableId.GetObject(OpenMode.ForRead) <span class="keyword">as</span> LinetypeTable;</span><br><span class="line">        <span class="keyword">if</span>(!lt.Has(linetypeName))</span><br><span class="line">            <span class="keyword">return</span> ObjectId.Null;</span><br><span class="line"></span><br><span class="line">        <span class="comment">//获取线型表记录对象</span></span><br><span class="line">        LinetypeTableRecord ltr = <span class="keyword">new</span> LinetypeTableRecord();</span><br><span class="line">        ltr = lt[linetypeName].GetObject(OpenMode.ForRead) <span class="keyword">as</span> LinetypeTableRecord;</span><br><span class="line">        <span class="keyword">return</span> ltr.ObjectId;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<blockquote>
<p>在 AutoCAD 中，颜色通过数字索引来表示，其中不同的数字对应于不同的颜色。AutoCAD 使用 Aci 颜色体系（AutoCAD Color Index）来定义颜色。</p>
<p>以下是一些常见的 Aci 颜色索引及其对应的颜色：</p>
<ul>
<li>1: 红色</li>
<li>2: 黄色</li>
<li>3: 绿色</li>
<li>4: 青色</li>
<li>5: 蓝色</li>
<li>6: 品红</li>
<li>7: 白色</li>
<li>8: 灰色</li>
<li>9: 深红色</li>
<li>10: 深黄色</li>
<li>30: 橙色</li>
<li>40: 棕色</li>
<li>90: 深绿色</li>
<li>91: 深青色</li>
<li>92: 深蓝色</li>
<li>93: 深品红</li>
<li>94: 深灰色</li>
<li>95: 浅灰色</li>
</ul>
</blockquote>
<h2 id="How-to-create-spline"><a href="#How-to-create-spline" class="headerlink" title="How to create spline"></a>How to create spline</h2><p>[c#样条曲线命令_AutoCAD 2019 你真的了解样条曲线吗？_养兔子的大叔的博客-CSDN博客](<a target="_blank" rel="noopener" href="https://blog.csdn.net/weixin_32568425/article/details/112450227#:~:text=c%23%E6%A0%B7%E6%9D%A1%E6%9B%B2%E7%BA%BF%E5%91%BD%E4%BB%A4_AutoCAD">https://blog.csdn.net/weixin_32568425/article/details/112450227#:~:text=c%23样条曲线命令_AutoCAD</a> 2019 你真的了解样条曲线吗？ 1 5.18.1、样条曲线 创建经过或靠近一组 拟合点 或由,拟合点 或 控制点 进行定义。 默认情况下，拟合点与样条曲线重合，而控制点定义控制框。 控制框提供了一种便捷的方法，用来设置样条曲线的形状。 每种方法都有其优点。 )</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">using</span> System;</span><br><span class="line"><span class="keyword">using</span> System.Collections.Generic;</span><br><span class="line"><span class="keyword">using</span> System.Linq;</span><br><span class="line"><span class="keyword">using</span> System.Text;</span><br><span class="line"><span class="keyword">using</span> System.Threading.Tasks;</span><br><span class="line"></span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.ApplicationServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.DatabaseServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.EditorInput;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Geometry;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Runtime;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Colors;</span><br><span class="line"></span><br><span class="line"><span class="keyword">namespace</span> <span class="title">CivilWorkDrawing</span></span><br><span class="line">&#123;  </span><br><span class="line"></span><br><span class="line">	[<span class="meta">CommandMethod(<span class="string">&quot;CreateSpline&quot;</span>)</span>]</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">CreateSpline</span>()</span></span><br><span class="line">    &#123;</span><br><span class="line">        Document doc = Application.DocumentManager.MdiActiveDocument;</span><br><span class="line">        Editor ed = doc.Editor;</span><br><span class="line">        Database db = doc.Database;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">using</span> (Transaction tr = db.TransactionManager.StartTransaction())</span><br><span class="line">        &#123;</span><br><span class="line">            BlockTable bt = tr.GetObject(db.BlockTableId, OpenMode.ForWrite) <span class="keyword">as</span> BlockTable;</span><br><span class="line">            BlockTableRecord currentSpace = tr.GetObject(db.CurrentSpaceId, OpenMode.ForWrite) <span class="keyword">as</span> BlockTableRecord;</span><br><span class="line"></span><br><span class="line">            <span class="comment">//determine the control points</span></span><br><span class="line">            Point3dCollection controlPoints = <span class="keyword">new</span> Point3dCollection();</span><br><span class="line">            Point3d startPoint = <span class="keyword">new</span> Point3d(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            controlPoints.Add(startPoint);</span><br><span class="line"></span><br><span class="line">            Point3d controlPoint01 = <span class="keyword">new</span> Point3d(<span class="number">-120</span>, <span class="number">194</span>, <span class="number">0</span>);</span><br><span class="line">            controlPoints.Add(controlPoint01);</span><br><span class="line"></span><br><span class="line">            Point3d controlPoint02 = <span class="keyword">new</span> Point3d(<span class="number">-93</span> + <span class="number">22</span>, <span class="number">470</span> - <span class="number">147</span>, <span class="number">0</span>);</span><br><span class="line">            controlPoints.Add(controlPoint02);</span><br><span class="line"></span><br><span class="line">            Point3d endPoint = <span class="keyword">new</span> Point3d(<span class="number">-93</span>, <span class="number">470</span>, <span class="number">0</span>);</span><br><span class="line">            controlPoints.Add(endPoint);</span><br><span class="line"></span><br><span class="line">            <span class="comment">//create the spline curve</span></span><br><span class="line">            <span class="comment">//Spline splineCurve = new Spline(controlPoints, 0.0, 0.0, 0.0, 1.0);</span></span><br><span class="line">            Spline splineCurve = <span class="keyword">new</span> Spline();</span><br><span class="line">            <span class="keyword">for</span>(<span class="built_in">int</span> i=<span class="number">0</span>;i&lt;controlPoints.Count;i++)</span><br><span class="line">            &#123;</span><br><span class="line">                splineCurve.SetControlPointAt(i,controlPoints[i]);</span><br><span class="line">            &#125;</span><br><span class="line"></span><br><span class="line">            currentSpace.AppendEntity(splineCurve);</span><br><span class="line">            tr.AddNewlyCreatedDBObject(splineCurve, <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">            tr.Commit();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

</article><div class="post-copyright"><div class="post-copyright__author"><span class="post-copyright-meta">Author: </span><span class="post-copyright-info"><a href="https://rainbow-runner.github.io">Rainbow Runner</a></span></div><div class="post-copyright__type"><span class="post-copyright-meta">Link: </span><span class="post-copyright-info"><a href="https://rainbow-runner.github.io/2023/08/08/DrawCivilWorkDrawingViaAPI/">https://rainbow-runner.github.io/2023/08/08/DrawCivilWorkDrawingViaAPI/</a></span></div><div class="post-copyright__notice"><span class="post-copyright-meta">Copyright Notice: </span><span class="post-copyright-info">All articles in this blog are licensed under <a target="_blank" rel="noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> unless stating additionally.</span></div></div><div class="tag_share"><div class="post-meta__tag-list"></div><div class="post_share"><div class="social-share" data-image="https://s3.bmp.ovh/imgs/2023/01/21/b9b5ab8e8b18eac5.jpg" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><div class="prev-post pull-left"><a href="/2023/08/09/How-Three-Phase-Electricity-Works/"><img class="prev-cover" src="https://s3.bmp.ovh/imgs/2023/08/10/a7e998d06a3fcf6c.jpg" onerror="onerror=null;src='/img/404.jpg'" alt="cover of previous post"><div class="pagination-info"><div class="label">Previous Post</div><div class="prev_info">How Three Phase Electricity Works</div></div></a></div><div class="next-post pull-right"><a href="/2023/03/12/Plant3DAPI-Examples/"><img class="next-cover" src="https://s3.bmp.ovh/imgs/2023/01/21/b9b5ab8e8b18eac5.jpg" onerror="onerror=null;src='/img/404.jpg'" alt="cover of next post"><div class="pagination-info"><div class="label">Next Post</div><div class="next_info">Plant3DAPI-Examples</div></div></a></div></nav></div><div class="aside-content" id="aside-content"><div class="card-widget card-info"><div class="is-center"><div class="avatar-img"><img src="https://i.loli.net/2021/02/24/5O1day2nriDzjSu.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info__name">Rainbow Runner</div><div class="author-info__description"></div></div><div class="card-info-data site-data is-center"><a href="/archives/"><div class="headline">Articles</div><div class="length-num">17</div></a><a href="/tags/"><div class="headline">Tags</div><div class="length-num">2</div></a><a href="/categories/"><div class="headline">Categories</div><div class="length-num">0</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/xxxxxx"><i class="fab fa-github"></i><span>Follow Me</span></a></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>Announcement</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>Catalog</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-2"><a class="toc-link" href="#Intruduction"><span class="toc-number">1.</span> <span class="toc-text">Intruduction</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#How-to-create-and-add-the-entity-to-the-block"><span class="toc-number">2.</span> <span class="toc-text">How to create and add the entity to the block</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#How-to-create-new-layer-and-set-the-line-type-and-the-line-color"><span class="toc-number">3.</span> <span class="toc-text">How to create new layer and set the line type and  the line color</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#How-to-create-spline"><span class="toc-number">4.</span> <span class="toc-text">How to create spline</span></a></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>Recent Post</span></div><div class="aside-list"><div class="aside-list-item"><a class="thumbnail" href="/2023/08/16/Plant3D-PythonCustomScripts-InsulationKits/" title="Plant3D-Python Custom Scripts-Insulation Kits"><img src="https://s3.bmp.ovh/imgs/2023/01/21/b9b5ab8e8b18eac5.jpg" onerror="this.onerror=null;this.src='/img/404.jpg'" alt="Plant3D-Python Custom Scripts-Insulation Kits"/></a><div class="content"><a class="title" href="/2023/08/16/Plant3D-PythonCustomScripts-InsulationKits/" title="Plant3D-Python Custom Scripts-Insulation Kits">Plant3D-Python Custom Scripts-Insulation Kits</a><time datetime="2023-08-16T13:58:25.000Z" title="Created 2023-08-16 21:58:25">2023-08-16</time></div></div><div class="aside-list-item"><a class="thumbnail" href="/2023/08/13/ThermodynamicsAnEngineeringApproach/" title="Thermodynamics An Engineering Approach"><img src="https://s3.bmp.ovh/imgs/2023/08/13/f03471ff1da4950b.jpg" onerror="this.onerror=null;this.src='/img/404.jpg'" alt="Thermodynamics An Engineering Approach"/></a><div class="content"><a class="title" href="/2023/08/13/ThermodynamicsAnEngineeringApproach/" title="Thermodynamics An Engineering Approach">Thermodynamics An Engineering Approach</a><time datetime="2023-08-12T17:50:15.000Z" title="Created 2023-08-13 01:50:15">2023-08-13</time></div></div><div class="aside-list-item"><a class="thumbnail" href="/2023/08/09/How-Three-Phase-Electricity-Works/" title="How Three Phase Electricity Works"><img src="https://s3.bmp.ovh/imgs/2023/08/10/a7e998d06a3fcf6c.jpg" onerror="this.onerror=null;this.src='/img/404.jpg'" alt="How Three Phase Electricity Works"/></a><div class="content"><a class="title" href="/2023/08/09/How-Three-Phase-Electricity-Works/" title="How Three Phase Electricity Works">How Three Phase Electricity Works</a><time datetime="2023-08-09T12:31:28.000Z" title="Created 2023-08-09 20:31:28">2023-08-09</time></div></div><div class="aside-list-item"><a class="thumbnail" href="/2023/08/08/DrawCivilWorkDrawingViaAPI/" title="Draw Civil Work Drawing Via API &amp; C#"><img src="https://s3.bmp.ovh/imgs/2023/01/21/b9b5ab8e8b18eac5.jpg" onerror="this.onerror=null;this.src='/img/404.jpg'" alt="Draw Civil Work Drawing Via API &amp; C#"/></a><div class="content"><a class="title" href="/2023/08/08/DrawCivilWorkDrawingViaAPI/" title="Draw Civil Work Drawing Via API &amp; C#">Draw Civil Work Drawing Via API &amp; C#</a><time datetime="2023-08-08T12:41:15.000Z" title="Created 2023-08-08 20:41:15">2023-08-08</time></div></div><div class="aside-list-item"><a class="thumbnail" href="/2023/03/12/Plant3DAPI-Examples/" title="Plant3DAPI-Examples"><img src="https://s3.bmp.ovh/imgs/2023/01/21/b9b5ab8e8b18eac5.jpg" onerror="this.onerror=null;this.src='/img/404.jpg'" alt="Plant3DAPI-Examples"/></a><div class="content"><a class="title" href="/2023/03/12/Plant3DAPI-Examples/" title="Plant3DAPI-Examples">Plant3DAPI-Examples</a><time datetime="2023-03-11T21:30:12.000Z" title="Created 2023-03-12 05:30:12">2023-03-12</time></div></div></div></div></div></div></main><footer id="footer"><div id="footer-wrap"><div class="copyright">&copy;2020 - 2023 By Rainbow Runner</div><div class="framework-info"><span>Framework </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>Theme </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="Read Mode"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="Switch Between Light And Dark Mode"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="Toggle between single-column and double-column"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside_config" type="button" title="Setting"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="Table Of Contents"><i class="fas fa-list-ul"></i></button><button id="go-up" type="button" title="Back To Top"><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.umd.min.js"></script><div class="js-pjax"></div><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script></div></body></html>